// <auto-generated />
using ExamWeb_TranMinhTuyen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_TranMinhTuyen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_TranMinhTuyen.Models.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DienVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaDe")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Phim");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiaVe = 150.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Chúng ta của 8 năm sau"
                        },
                        new
                        {
                            Id = 2,
                            GiaVe = 150.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Avatar"
                        },
                        new
                        {
                            Id = 3,
                            GiaVe = 150.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Gặp em ngày nắng"
                        },
                        new
                        {
                            Id = 4,
                            GiaVe = 150.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Không ngại cười"
                        },
                        new
                        {
                            Id = 5,
                            GiaVe = 150.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Gia đình đại chiến"
                        },
                        new
                        {
                            Id = 6,
                            GiaVe = 150.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Kẻ huỷ diệt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
